version: '3.8'
services:
  db:
    image: postgres:15
    container_name: farmland-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: farmland
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: farmland-app
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  postgres_data:
